### PR TITLE
Extended support, documentation, and functionalities

### PR DESCRIPTION
**Pull request by silvavn**
1. Documented scholarly.py
2. Separated Scholarly, Publication and Author into different files
3. Added search_single_pub to Scholarly
4. Fixed bibtex collection and handled exceptions
5. Expanded support to Chrome and Firefox Webdrivers
6. Randomized Selenium features for both drivers.
7. Implemented a no-wait policy when using ToR, for faster study collection.
8. Implemented expanded error handling for traffic, automation and captchas,
9. Moved hardcoding to a json file for improved code maintenance

### CODE REVIEW

**Comment by janruh** [comment]
Thanks for your contribution. I will have a look as soon as I find the time;)

**Comment by janruh** [comment]
What do you mean by?

> removed the bib, since it was not working

**Comment by silvavn** [comment]
> What do you mean by?
> 
> > removed the bib, since it was not working

So when I was writing my code I realized that the bib part wasn't working (when you clicked on any bib it would return a 404). While it could be a bug from google server, now it works. In my latest version I did it differently.

**Comment by janruh** [comment]
Ah yes, I see. I was wondering since I checked your commits and couldn't figure out what you meant by 'removed the bib'.

**Pull request merged**
